config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :articles
  resources :categories
  resources :tags
  get '/admins', to: 'admins#index', as: :admins_path
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include FriendlyId
  friendly_id :title, use: :slugged

  has_and_belongs_to_many :categories, join_table: :articles_categories
  has_and_belongs_to_many :tags, join_table: :articles_tags

  enum access_level: {admin: 0, fuga_client: 5, fuga_public: 10}
end

app/models/category.rb
class Category < ApplicationRecord
  include FriendlyId
  friendly_id :title, use: :slugged
  has_and_belongs_to_many :articles, join_table: :articles_categories
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :articles, join_table: :articles_tags
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update]

  def index
    @articles = Article.all
  end

  def show
  end

  def edit
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(permitted_params)
    if @article.save
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def update
    access_level = {access_level: params[:article][:access_level].to_i}
    if @article.update(permitted_params.merge(access_level))
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  private

    def find_article
      @article = Article.friendly.find(params[:id])
    end

    def permitted_params
      params.require(:article).permit(:title, :content, tag_ids: [], category_ids: [])
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update]

  def index
    @categories = Category.all
  end

  def show
  end

  def edit
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(permitted_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def update
    if @category.update(permitted_params)
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  private

    def find_category
      @category = Category.friendly.find(params[:id])
    end

    def permitted_params
      params.require(:category).permit(:title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @categories = Category.order(:title)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :find_tag, only: [:edit, :update]

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(permitted_params)
    if @tag.save
      redirect_to tags_path
    else
      render :new
    end
  end

  def update
    if @tag.update(permitted_params)
      redirect_to tags_path
    else
      render :edit
    end
  end

  private

    def find_tag
      @tag = Tag.find(params[:id])
    end

    def permitted_params
      params.require(:tag).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/index.html.haml
.container
  .row
    .col-md-12
      = link_to 'create new article', new_article_path, class: ['btn', 'btn-primary']
  .row
    .col-md-12
      = link_to 'create new category', new_category_path, class: ['btn', 'btn-primary']
  .row
    .col-md-12
      = link_to 'create new tag', new_tag_path, class: ['btn', 'btn-primary']

app/views/articles/_form.html.haml
.container
  .row
    .col-md-6.offset-md-3
      = simple_form_for @article do |f|
        .form-group
          = f.input :title, input_html: {class: 'form-control'}
        .form-group
          = f.input :content, input_html: {class: 'form-control'}
        .form-group
          = f.label :access_level, 'Access_level'
          = f.select :access_level, Article.access_levels.map { |name, integer| [name, integer, { class: 'form-control' }] }, input_html: {class: 'form-control'}
        .form-group
          = f.association :tags, collection: Tag.all, input_html: {class: 'form-control'}
        .form-group
          = f.association :categories, collection: Category.all, input_html: {class: 'form-control'}
        .form-group
          = f.button :submit, input_html: {class: 'form-control'}

app/views/articles/edit.html.haml
= render 'form'

app/views/articles/index.html.haml
.index
  - @articles.each do |article|
    %p
      = link_to article.title, article_path(article)
    %p
      = article.content
    %ul
      - article.categories.each do |category|
        %li
          = category.title

app/views/articles/new.html.haml
= render 'form'

app/views/articles/show.html.haml
.container
  .row
    .col-md-12
      %p
        = @article.title
      .article-holder
        = @article.content

app/views/categories/_form.html.haml
.container
  .row
    .col-md-6.offset-md-3
      = simple_form_for @category do |f|
        .form-group
          = f.input :title, input_html: {class: 'form-control'}
        .form-group
          = f.button :submit, input_html: {class: 'form-control'}

app/views/categories/edit.html.haml
= render 'form'

app/views/categories/index.html.haml
.container
  .row
    .col-md-12
      - @categories.each do |category|
        %p
          = link_to category.title, category_path(category)
        %ul
          - category.articles.each do |article|
            %li
              = link_to article.title, article_path(article)

app/views/categories/new.html.haml
= render 'form'

app/views/categories/show.html.haml
.container
  .row
    .col-md-12
      %p
        = @category.title
      %ul
        - @category.articles.each do |article|
          %li
            = link_to article.title, article_path(article)

app/views/home/index.html.haml
.container
  .row
    .col-md-12
      %h2.text-center.my-4
        = 'Welcome to the FUGA Knowledge Base'
      - @categories.each do |category|
        %p
          = link_to category.title, category_path(category)
        %ul
          - category.articles.each do |article|
            %li
              = link_to article.title, article_path(article)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FUGA Knowledge Base</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_navbar.html.haml
%nav{ class: ['navbar', 'navbar-toggleable-md', 'navbar-light', 'bg-faded', 'main-navbar'], role: 'navigation' }
  %button{ class: ['navbar-toggler', 'navbar-toggler-right'], data: {toggle: 'collapse', target: "#navbarSupportedContent"} }
    %span.navbar-toggler-icon
  = link_to 'FUGA Knowledge Base', root_path, class: 'navbar-brand'
  %div{ class: ['collapse', 'navbar-collapse'], id: 'navbarSupportedContent' }
    %ul{ class: ['mr-auto', 'navbar-nav'] }
      %li.nav-item
        = link_to 'Articles', articles_path, class: 'nav-link'
      %li.nav-item
        = link_to 'Categories', categories_path, class: 'nav-link'
      %li.nav-item
        = link_to 'admin', admins_path_url, class: 'nav-link'

app/views/tags/_form.html.haml
.container
  .row
    .col-md-6.offset-md-3
      = simple_form_for @tag do |f|
        .form-group
          = f.input :title, input_html: {class: 'form-control'}
        .form-group
          = f.button :submit, input_html: {class: 'form-control'}

app/views/tags/edit.html.haml
= render 'form'

app/views/tags/index.html.haml
.container
  .row
    .col-md-12
      - @tags.each do |tag|
        .tag-holder
          = link_to tag.title, edit_tag_path(tag)

app/views/tags/new.html.haml
= render 'form'